name: lint

on:
  push:
    branches: 
      - main

env:
  POETRY_HOME: /opt/poetry

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Install poetry
        run: |
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          $POETRY_HOME/bin/poetry install
      - name: Run lint
        run: |
          $POETRY_HOME/bin/poetry run poe lint
      
      