name: lint

on:
  push:
    branches: 
      - main

env:
  POETRY_HOME: /opt/poetry

jobs:

  hashfiles: # as hashFiles function does not work in the python container
    runs-on: ubuntu-latest
    outputs:
      workflows-hash: ${{ steps.workflows-hash.outputs.hash }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - id: workflows-hash
        name: Let's hash .github/workflows/**
        run: echo "hash=${{ hashFiles('.github/workflows/**') }}" >> $GITHUB_OUTPUT
      - id: workflows-hash2
        name: Let's hash .github/workflows/**2
        run: echo "hash=${{ hashFiles('**/.github/workflows/*.yaml') }}" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    environment: ci
    container:
      image: python:3.9
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Cache poetry install
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.POETRY_HOME }}
          key: cache-${{ needs.hashfiles.outputs.workflows-hash }}-${{ vars.CACHE_VERSION }}
      - name: Install poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          $POETRY_HOME/bin/poetry install
      - name: Fix github path
        run: |
          echo "$POETRY_HOME/bin" >> $GITHUB_PATH
      - name: Run lint
        run: |
          poetry run poe lint
      
      
